create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  listing_id bigint not null references public.listings(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint favorites_user_id_listing_id_key unique (user_id, listing_id)
);

alter table public.favorites
  add column if not exists id bigint generated by default as identity,
  add column if not exists user_id uuid references auth.users(id) on delete cascade,
  add column if not exists listing_id bigint references public.listings(id) on delete cascade,
  add column if not exists created_at timestamptz default now();

do $$
declare
  primary_key_name text;
begin
  select constraint_name
    into primary_key_name
  from information_schema.table_constraints
  where table_schema = 'public'
    and table_name = 'favorites'
    and constraint_type = 'PRIMARY KEY';

  if primary_key_name is not null and primary_key_name <> 'favorites_id_pkey' then
    execute format(
      'alter table public.favorites drop constraint %I',
      primary_key_name
    );
  end if;

  if not exists (
    select 1
    from information_schema.table_constraints
    where table_schema = 'public'
      and table_name = 'favorites'
      and constraint_type = 'PRIMARY KEY'
  ) then
    alter table public.favorites
      add constraint favorites_id_pkey primary key (id);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from information_schema.table_constraints
    where table_schema = 'public'
      and table_name = 'favorites'
      and constraint_name = 'favorites_user_id_listing_id_key'
  ) then
    alter table public.favorites
      add constraint favorites_user_id_listing_id_key
      unique (user_id, listing_id);
  end if;
end
$$;

alter table public.favorites
  alter column id set not null,
  alter column user_id set not null,
  alter column listing_id set not null,
  alter column created_at set default now(),
  alter column created_at set not null;

create index if not exists favorites_listing_id_idx
  on public.favorites(listing_id);

alter table public.favorites enable row level security;

drop policy if exists "Users can read their favorites" on public.favorites;
create policy "Users can read their favorites"
  on public.favorites
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can add their favorites" on public.favorites;
create policy "Users can add their favorites"
  on public.favorites
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can remove their favorites" on public.favorites;
create policy "Users can remove their favorites"
  on public.favorites
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);
