-- 2ElBul price history.
-- Run this before or together with supabase/bot-sync.sql on existing projects.

create table if not exists public.price_history (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  listing_id bigint null references public.listings(id) on delete set null,
  source text not null,
  price bigint not null,
  recorded_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists price_history_product_recorded_at_idx
  on public.price_history(product_id, recorded_at);

create index if not exists price_history_listing_recorded_at_idx
  on public.price_history(listing_id, recorded_at);

alter table public.price_history enable row level security;

drop policy if exists "Public can read price history" on public.price_history;
create policy "Public can read price history"
  on public.price_history
  for select
  to anon, authenticated
  using (
    listing_id is null
    or exists (
      select 1
      from public.listings
      where listings.id = price_history.listing_id
        and listings.status in ('published', 'active')
    )
  );
