create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text unique,
  category text,
  created_at timestamptz not null default now()
);

alter table public.products
  add column if not exists name text,
  add column if not exists slug text,
  add column if not exists category text,
  add column if not exists created_at timestamptz default now();

create table if not exists public.listings (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete restrict,
  title text not null,
  external_id text,
  price numeric(12, 2) not null check (price > 0),
  previous_price numeric(12, 2),
  price_updated_at timestamptz,
  city text not null,
  source text not null,
  url text not null,
  condition text not null,
  image_url text,
  status text not null default 'published'
    check (status in ('pending', 'published', 'rejected')),
  published_at timestamptz,
  imported_at timestamptz,
  raw_payload jsonb,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.listings
  add column if not exists product_id bigint,
  add column if not exists title text,
  add column if not exists external_id text,
  add column if not exists price numeric(12, 2),
  add column if not exists previous_price numeric(12, 2),
  add column if not exists price_updated_at timestamptz,
  add column if not exists city text,
  add column if not exists source text,
  add column if not exists url text,
  add column if not exists condition text,
  add column if not exists image_url text,
  add column if not exists status text default 'published',
  add column if not exists published_at timestamptz,
  add column if not exists imported_at timestamptz,
  add column if not exists raw_payload jsonb,
  add column if not exists user_id uuid references auth.users(id) on delete set null,
  add column if not exists created_at timestamptz default now();

create table if not exists public.search_events (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  query text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  listing_id bigint not null references public.listings(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint favorites_user_id_listing_id_key unique (user_id, listing_id)
);

create table if not exists public.price_alerts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  target_price numeric(12, 2) not null check (target_price > 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists listings_product_id_idx
  on public.listings(product_id);

create index if not exists listings_created_at_idx
  on public.listings(created_at desc);

create index if not exists listings_user_id_idx
  on public.listings(user_id);

create unique index if not exists listings_source_external_id_key
  on public.listings(source, external_id);

create index if not exists listings_price_updated_at_idx
  on public.listings(price_updated_at desc);

create index if not exists search_events_product_id_idx
  on public.search_events(product_id);

create index if not exists search_events_created_at_idx
  on public.search_events(created_at desc);

create index if not exists favorites_listing_id_idx
  on public.favorites(listing_id);

create index if not exists price_alerts_user_id_idx
  on public.price_alerts(user_id);

create or replace function public.track_listing_price_change()
returns trigger
language plpgsql
as $$
begin
  if new.price is distinct from old.price then
    new.previous_price := old.price;
    new.price_updated_at := now();
  end if;

  return new;
end;
$$;

drop trigger if exists listings_track_price_change on public.listings;
create trigger listings_track_price_change
  before update of price on public.listings
  for each row
  execute function public.track_listing_price_change();

alter table public.products enable row level security;
alter table public.listings enable row level security;
alter table public.search_events enable row level security;
alter table public.favorites enable row level security;
alter table public.price_alerts enable row level security;

drop policy if exists "Products are publicly readable" on public.products;
create policy "Products are publicly readable"
  on public.products
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Listings are publicly readable" on public.listings;
create policy "Listings are publicly readable"
  on public.listings
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Anyone can submit listings" on public.listings;
create policy "Anyone can submit listings"
  on public.listings
  for insert
  to anon, authenticated
  with check (user_id is null or (select auth.uid()) = user_id);

drop policy if exists "Search events are publicly readable" on public.search_events;
create policy "Search events are publicly readable"
  on public.search_events
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Anyone can record searches" on public.search_events;
create policy "Anyone can record searches"
  on public.search_events
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Users can read their favorites" on public.favorites;
create policy "Users can read their favorites"
  on public.favorites
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can add their favorites" on public.favorites;
create policy "Users can add their favorites"
  on public.favorites
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can remove their favorites" on public.favorites;
create policy "Users can remove their favorites"
  on public.favorites
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can read their price alerts" on public.price_alerts;
create policy "Users can read their price alerts"
  on public.price_alerts
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can add their price alerts" on public.price_alerts;
create policy "Users can add their price alerts"
  on public.price_alerts
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their price alerts" on public.price_alerts;
create policy "Users can update their price alerts"
  on public.price_alerts
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can remove their price alerts" on public.price_alerts;
create policy "Users can remove their price alerts"
  on public.price_alerts
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);

insert into public.products (name, category)
values
  ('RTX 2060 Super', 'Ekran Kartı'),
  ('i5-12400F', 'İşlemci'),
  ('iPhone 13', 'Telefon'),
  ('PS5', 'Oyun Konsolu'),
  ('MacBook Air M1', 'Laptop')
on conflict (name) do update
set category = excluded.category;
