create table if not exists public.sources (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique not null,
  base_url text null,
  type text not null default 'marketplace',
  is_active boolean not null default true,
  bot_listing_status text not null default 'pending'
    check (bot_listing_status in ('pending', 'published')),
  last_run_at timestamptz null,
  total_imported bigint not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.bot_runs (
  id bigint generated by default as identity primary key,
  source_id bigint references public.sources(id) on delete cascade,
  status text not null default 'pending',
  run_type text not null default 'manual',
  started_at timestamptz null,
  finished_at timestamptz null,
  found_count int not null default 0,
  imported_count int not null default 0,
  skipped_count int not null default 0,
  error_count int not null default 0,
  error_message text null,
  created_at timestamptz not null default now()
);

create index if not exists sources_is_active_idx
  on public.sources(is_active);

create index if not exists bot_runs_source_id_created_at_idx
  on public.bot_runs(source_id, created_at desc);

create index if not exists bot_runs_status_created_at_idx
  on public.bot_runs(status, created_at desc);

alter table public.sources enable row level security;
alter table public.bot_runs enable row level security;

alter table public.sources
  add column if not exists bot_listing_status text not null default 'pending';

alter table public.sources
  drop constraint if exists sources_bot_listing_status_check;

alter table public.sources
  add constraint sources_bot_listing_status_check
  check (bot_listing_status in ('pending', 'published'));

insert into public.sources (
  name,
  slug,
  base_url,
  type,
  bot_listing_status
)
values
  ('Sahibinden', 'sahibinden', 'https://www.sahibinden.com', 'marketplace', 'pending'),
  ('Letgo', 'letgo', 'https://www.letgo.com', 'marketplace', 'pending'),
  ('Facebook Marketplace', 'facebook-marketplace', 'https://www.facebook.com/marketplace', 'marketplace', 'pending'),
  ('EasyCep', 'easycep', 'https://easycep.com', 'refurbished', 'published'),
  ('Getmobil', 'getmobil', 'https://getmobil.com', 'refurbished', 'pending'),
  ('Yenilenmiş Market', 'yenilenmis-market', 'https://yenilenmismarket.com', 'refurbished', 'pending'),
  ('Teknosa Yenilenmiş', 'teknosa-yenilenmis', 'https://www.teknosa.com', 'refurbished', 'pending'),
  ('Hepsiburada Yenilenmiş', 'hepsiburada-yenilenmis', 'https://www.hepsiburada.com', 'refurbished', 'pending'),
  ('MediaMarkt Yenilenmiş', 'mediamarkt-yenilenmis', 'https://www.mediamarkt.com.tr', 'refurbished', 'pending')
on conflict (slug) do update
set
  name = excluded.name,
  base_url = excluded.base_url,
  type = excluded.type;
