export type { NormalizationOptions, ProductSignals, InferConditionResult } from './engine';
export {
  normalizeProductTitle,
  normalizeSearchText,
  normalizeCategoryText,
  normalizeListingTitle,
  normalizeQuery,
  normalizeSlug,
  normalizeKeyword,
  extractStorageSize,
  extractBrand,
  formatBrandDisplayName,
  isBareIphoneModel,
  isBareSamsungModel,
  getTokens,
  createSearchFingerprint,
  isSimilarAfterNormalization,
  extractProductSignals,
  generateProductKey,
  inferCondition,
  detectModel,
} from './engine';
