-- Migration: Add search_events table (was defined in schema.sql but never migrated to production)
-- This table tracks search queries from category/brand/city pages and the search action.
-- It feeds the "search demand" sections on category/brand/city pages and home page trends.

create table if not exists public.search_events (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  query text not null,
  created_at timestamptz not null default now()
);

create index if not exists search_events_product_id_idx
  on public.search_events(product_id);

create index if not exists search_events_created_at_idx
  on public.search_events(created_at desc);

alter table public.search_events enable row level security;

drop policy if exists "Search events are publicly readable" on public.search_events;
create policy "Search events are publicly readable"
  on public.search_events
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Anyone can record searches" on public.search_events;
create policy "Anyone can record searches"
  on public.search_events
  for insert
  to anon, authenticated
  with check (true);
