-- Reliable price history tracking and safe backfill support.
-- Run after supabase/price-history.sql and supabase/bot-sync.sql.

create table if not exists public.price_history (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  listing_id bigint null references public.listings(id) on delete set null,
  source text not null default 'Bilinmeyen kaynak',
  price bigint not null,
  recorded_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.price_history
  add column if not exists source text not null default 'Bilinmeyen kaynak',
  add column if not exists recorded_at timestamptz not null default now(),
  add column if not exists created_at timestamptz not null default now();

create index if not exists price_history_listing_price_recorded_at_idx
  on public.price_history(listing_id, price, recorded_at);

create index if not exists price_history_product_recorded_at_idx
  on public.price_history(product_id, recorded_at);

create or replace function public.record_listing_price_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.product_id is null or new.id is null or new.price is null then
    return new;
  end if;

  if tg_op = 'UPDATE' and old.price is not distinct from new.price then
    return new;
  end if;

  insert into public.price_history (
    product_id,
    listing_id,
    source,
    price,
    recorded_at
  )
  select
    new.product_id,
    new.id,
    coalesce(nullif(new.source, ''), 'Bilinmeyen kaynak'),
    new.price::bigint,
    now()
  where not exists (
    select 1
    from public.price_history history
    where history.listing_id = new.id
      and history.price = new.price::bigint
      and history.recorded_at >= date_trunc('day', now())
      and history.recorded_at < date_trunc('day', now()) + interval '1 day'
  );

  return new;
end;
$$;

drop trigger if exists listings_record_price_history on public.listings;
create trigger listings_record_price_history
  after insert or update of price on public.listings
  for each row
  execute function public.record_listing_price_history();

create or replace function public.backfill_price_history_from_listings(
  p_limit int default 500,
  p_dry_run boolean default true
)
returns table(candidate_count int, inserted_count int)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_candidate_count int := 0;
  v_inserted_count int := 0;
begin
  with candidates as (
    select
      listing.id,
      listing.product_id,
      coalesce(nullif(listing.source, ''), 'Bilinmeyen kaynak') as source,
      listing.price
    from public.listings listing
    where listing.product_id is not null
      and listing.price is not null
      and listing.price > 0
      and coalesce(listing.status, 'published') in ('published', 'active')
      and not exists (
        select 1
        from public.price_history history
        where history.listing_id = listing.id
          and history.price = listing.price::bigint
      )
    order by listing.created_at desc nulls last, listing.id desc
    limit greatest(coalesce(p_limit, 500), 1)
  )
  select count(*) into v_candidate_count from candidates;

  if not p_dry_run then
    with candidates as (
      select
        listing.id,
        listing.product_id,
        coalesce(nullif(listing.source, ''), 'Bilinmeyen kaynak') as source,
        listing.price
      from public.listings listing
      where listing.product_id is not null
        and listing.price is not null
        and listing.price > 0
        and coalesce(listing.status, 'published') in ('published', 'active')
        and not exists (
          select 1
          from public.price_history history
          where history.listing_id = listing.id
            and history.price = listing.price::bigint
        )
      order by listing.created_at desc nulls last, listing.id desc
      limit greatest(coalesce(p_limit, 500), 1)
    ),
    inserted as (
      insert into public.price_history (
        product_id,
        listing_id,
        source,
        price,
        recorded_at
      )
      select
        product_id,
        id,
        source,
        price::bigint,
        now()
      from candidates
      returning 1
    )
    select count(*) into v_inserted_count from inserted;
  end if;

  return query select v_candidate_count, v_inserted_count;
end;
$$;
